"""The Teal mark, and where it is allowed to appear.

One module so the logo has a single path, a single set of dimensions and a
single answer to "what colour is the brand". Every document that carries it —
report PDFs, workbooks, certificates — reads from here, which is what stops the
mark from drifting to three sizes and two greens across the deliverables.

The file is bundled with the backend rather than fetched from the frontend's
`public/`: a certificate must render identically whether it is generated by the
API, a Celery worker, or a script, and only one of those has a web server in
front of it.
"""

import functools
import logging
import pathlib

log = logging.getLogger(__name__)

ASSETS = pathlib.Path(__file__).resolve().parent.parent / "assets"

# The mark, in the two grounds it is drawn on. Green for paper and light
# surfaces; white for dark ones. There is no third variant — recolouring a logo
# to fit a background is how a brand ends up with nine of them.
LOGO_GREEN = ASSETS / "teal-logo-green.png"
LOGO_WHITE = ASSETS / "teal-logo-white.png"

# The logo is square-ish with generous internal padding, so a naive placement
# leaves it looking small. Trimmed aspect is close enough to 1:1 to treat as
# square when reserving space.
LOGO_ASPECT = 964 / 931

TEAL = "#16A79E"       # the mark's own green
TEAL_DARK = "#0F766E"  # the app's accent, used for rules and headings
INK = "#14171A"
MUTED = "#64748B"
PAPER = "#FBFBF9"


@functools.lru_cache(maxsize=2)
def logo_path(on_dark: bool = False) -> str | None:
    """Absolute path to the mark, or None if it is not bundled.

    Returns None rather than raising: a missing logo should cost a document its
    letterhead, not its existence. Every caller draws a text wordmark instead.
    """
    path = LOGO_WHITE if on_dark else LOGO_GREEN
    if path.exists():
        return str(path)
    log.warning("branding: %s is missing — documents will fall back to text", path.name)
    return None


def verification_code(kind: str, record_id: int, learner_id: int) -> str:
    """A short, human-readable reference printed on issued documents.

    Deterministic from the record, so the same certificate always carries the
    same code and a support request can be answered by regenerating it rather
    than by storing another column. It identifies, it does not authenticate —
    anyone can compute one, so it belongs on a document, not on an API.
    """
    stamp = f"{kind[:3].upper()}-{record_id:05d}-{learner_id:04d}"
    return stamp
